import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader
import pandas as pd
import numpy as np
import os # Import os for path manipulation
import json # Import json for loading normalization params

# --- 1. Define Dataset ---
class PairedFeatureDataset(Dataset):
    def __init__(self, image_features_df, sound_features_df):
        # Ensure image_features_df and sound_features_df have matching indices/order
        # For simplicity, assuming they are already aligned by image/audio file name
        self.image_features = torch.tensor(image_features_df.values, dtype=torch.float32)
        self.sound_features = torch.tensor(sound_features_df.values, dtype=torch.float32)

        if len(self.image_features) != len(self.sound_features):
            raise ValueError("Number of image features must match number of sound features.")

    def __len__(self):
        return len(self.image_features)

    def __getitem__(self, idx):
        return self.image_features[idx], self.sound_features[idx]

# --- 2. Define the Linear Transformation Model ---
class LinearTransformation(nn.Module):
    def __init__(self, input_dim, output_dim):
        super(LinearTransformation, self).__init__()
        self.transform_layer = nn.Linear(input_dim, output_dim, bias=False)

    def forward(self, x):
        return self.transform_layer(x)

# --- 3. Load prepared data ---
# Load image features
image_features_df = pd.read_csv("feature_vectors.csv", index_col=0)

# --- NEW: Standardize image_features_df index to match sound feature names ---
# Assuming image_features_df index contains filenames like 'script.jpg', 'rhythm.png', etc.
# We need to strip the file extensions to match 'script', 'rhythm', 'echoes'
image_features_df.index = image_features_df.index.map(lambda x: os.path.splitext(x)[0])

# Load sound features (generated by extract_and_normalize_sound_features.py)
try:
    sound_features_df = pd.read_csv("sound_features_normalized.csv", index_col=0)
    
    # --- Critical Alignment Step ---
    # After stripping extensions, ensure both DataFrames have the same index values
    # and sort them to ensure corresponding rows align
    common_indices = sorted(list(set(image_features_df.index) & set(sound_features_df.index)))
    
    if not common_indices:
        raise ValueError("No common file names found between image_features_df and sound_features_df after index processing. Please check your data files.")

    image_features_df = image_features_df.loc[common_indices]
    sound_features_df = sound_features_df.loc[common_indices]
    
    # --- Load normalization parameters for denormalization ---
    with open("sound_normalization_params.json", 'r') as f:
        norm_params = json.load(f)
    original_sound_min_values = np.array(norm_params['min_values'])
    original_sound_max_values = np.array(norm_params['max_values'])

except FileNotFoundError:
    print("ERROR: Required 'sound_features_normalized.csv' or 'sound_normalization_params.json' not found.")
    print("Please run 'extract_and_normalize_sound_features.py' first to generate these files.")
    # Exit or raise an error, as training with dummy data here is not meaningful
    raise FileNotFoundError("Cannot proceed without actual sound features. Please generate them.")

# Convert to tensors
original_sound_min_values_tensor = torch.tensor(original_sound_min_values, dtype=torch.float32)
original_sound_max_values_tensor = torch.tensor(original_sound_max_values, dtype=torch.float32)


# --- 4. Initialize Dataset and DataLoader ---
dataset = PairedFeatureDataset(image_features_df, sound_features_df)
dataloader = DataLoader(dataset, batch_size=32, shuffle=True) # Shuffle for better training

# --- 5. Model, Loss, Optimizer ---
INPUT_DIM = image_features_df.shape[1] # Dynamically get input dimension
OUTPUT_DIM = sound_features_df.shape[1] # Dynamically get output dimension

model = LinearTransformation(INPUT_DIM, OUTPUT_DIM)
criterion = nn.MSELoss() # Mean Squared Error is common for regression
optimizer = optim.Adam(model.parameters(), lr=0.001) # Adam optimizer

# --- 6. Training Loop ---
num_epochs = 100 # Adjust as needed
print("\nStarting training...")
for epoch in range(num_epochs):
    for image_batch, sound_batch_true in dataloader:
        # Forward pass
        sound_batch_pred = model(image_batch)
        loss = criterion(sound_batch_pred, sound_batch_true)

        # Backward and optimize
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

    if (epoch+1) % 10 == 0:
        print(f'Epoch [{epoch+1}/{num_epochs}], Loss: {loss.item():.4f}')

print("Training finished.")

# --- 7. Save the T matrix (model weights) ---
T_matrix = model.transform_layer.weight.data
torch.save(T_matrix, "T_matrix.pt")
print(f"Transformation matrix T saved to T_matrix.pt with shape: {T_matrix.shape}")


### Part 3: Applying the Transformation and Enforcing Ranges

#Now that we have `T_matrix.pt`, we can use it to transform new image features.


# --- 8. Load the T matrix for inference ---
loaded_T_matrix = torch.load("T_matrix.pt")

# --- Example: Transform a single new image feature vector ---
# For demo, let's take the first image feature from our loaded data
new_image_feature_x = torch.tensor(image_features_df.iloc[0].values, dtype=torch.float32).unsqueeze(0) # unsqueeze for batch dim

with torch.no_grad(): # No need to calculate gradients for inference
    # y_pred_normalized will be in the same normalized range as our training sound features (e.g., [0,1])
    y_pred_normalized = (new_image_feature_x @ loaded_T_matrix.T).squeeze(0) # Transpose T because nn.Linear works with xA^T

    # --- Enforce Precise Ranges (Denormalization & Clamping) ---

    # 1. Denormalize the predicted sound features back to their original scales
    y_pred_original_scale = y_pred_normalized * (original_sound_max_values_tensor - original_sound_min_values_tensor) + original_sound_min_values_tensor

    # 2. Clamp to ensure values stay within physical/perceptual bounds
    y_pred_clamped = torch.max(original_sound_min_values_tensor, torch.min(original_sound_max_values_tensor, y_pred_original_scale))


print("\n--- Inference Example ---")
print(f"Input Image Feature Shape: {new_image_feature_x.shape}")
print(f"Predicted Normalized Sound Feature (y_pred_normalized): {y_pred_normalized.numpy()}")
print(f"Predicted Denormalized Sound Feature (y_pred_original_scale): {y_pred_original_scale.numpy()}")
print(f"Predicted Clamped Sound Feature (y_pred_clamped): {y_pred_clamped.numpy()}")
